#!/usr/bin/env python3
"""Extract HSV percentile statistics from classifier crop dataset."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

try:
    import cv2
except ModuleNotFoundError as exc:
    raise SystemExit("OpenCV required: pip install opencv-python") from exc

CLASSES = ("red", "green", "yellow", "off")
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp"}


def load_crop_images(crops_root: Path, class_name: str) -> list[np.ndarray]:
    images: list[np.ndarray] = []
    for split in ("train", "val"):
        class_dir = crops_root / split / class_name
        if not class_dir.exists():
            continue
        for p in class_dir.iterdir():
            if p.suffix.lower() not in IMAGE_EXTS:
                continue
            img = cv2.imread(str(p), cv2.IMREAD_COLOR)
            if img is not None:
                images.append(img)
    return images


def compute_hsv_percentiles(
    class_images: dict[str, list[np.ndarray]],
) -> dict[str, dict[str, float]]:
    results: dict[str, dict[str, float]] = {}
    for class_name, images in class_images.items():
        if not images:
            continue

        h_vals: list[float] = []
        s_vals: list[float] = []
        v_vals: list[float] = []

        for bgr in images:
            hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV).reshape(-1, 3).astype(np.float32)
            h_vals.extend((hsv[:, 0] * 2.0).tolist())
            s_vals.extend((hsv[:, 1] / 255.0).tolist())
            v_vals.extend((hsv[:, 2] / 255.0).tolist())

        results[class_name] = {
            "h_p05": float(np.percentile(h_vals, 5)),
            "h_p95": float(np.percentile(h_vals, 95)),
            "s_p05": float(np.percentile(s_vals, 5)),
            "s_p95": float(np.percentile(s_vals, 95)),
            "v_p05": float(np.percentile(v_vals, 5)),
            "v_p95": float(np.percentile(v_vals, 95)),
            "sample_count": float(len(h_vals)),
        }

    return results


def format_swift_ranges(stats: dict[str, dict[str, float]]) -> str:
    lines = ["// Calibrated HSV ranges - generated by calibrate_hsv.py"]
    lines.append("// Replace corresponding ColorHeuristic.swift classifyHSV() lines")
    lines.append("")

    for cls in ("red", "green", "yellow"):
        if cls not in stats:
            continue
        s = stats[cls]
        h05, h95 = s["h_p05"], s["h_p95"]
        s05 = s["s_p05"]
        v05 = s["v_p05"]
        n = int(s["sample_count"])

        if cls == "red":
            lines.append(f"// RED: h 5th={h05:.1f}deg 95th={h95:.1f}deg s>={s05:.2f} v>={v05:.2f} n={n}")
            lines.append(f"let isRed = (h <= {min(h05, 20):.0f} || h >= {max(h95, 340):.0f}) && s > {s05:.2f} && v > {v05:.2f}")
        elif cls == "green":
            lines.append(f"// GREEN: h 5th={h05:.1f}deg 95th={h95:.1f}deg s>={s05:.2f} v>={v05:.2f} n={n}")
            lines.append(f"let isGreen = (h >= {h05:.0f} && h <= {h95:.0f}) && s > {s05:.2f} && v > {v05:.2f}")
        elif cls == "yellow":
            lines.append(f"// YELLOW: h 5th={h05:.1f}deg 95th={h95:.1f}deg s>={s05:.2f} v>={v05:.2f} n={n}")
            lines.append(f"let isYellow = (h >= {h05:.0f} && h <= {h95:.0f}) && s > {s05:.2f} && v > {v05:.2f}")
        lines.append("")

    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Calibrate ColorHeuristic HSV ranges from crop dataset")
    parser.add_argument("--crops-root", type=Path, default=Path("export/datasets/crops/traffic_state"))
    parser.add_argument("--out-json", type=Path, default=None)
    parser.add_argument("--classes", nargs="+", default=list(CLASSES))
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    class_images: dict[str, list[np.ndarray]] = {}
    for cls in args.classes:
        images = load_crop_images(args.crops_root, cls)
        print(f"{cls}: {len(images)} crops loaded")
        class_images[cls] = images

    stats = compute_hsv_percentiles(class_images)

    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(json.dumps(stats, indent=2) + "\n")
        print(f"Stats saved to {args.out_json}")

    print("\n--- Recommended Swift ranges ---")
    print(format_swift_ranges(stats))
    print("\nUpdate GreenLight/Detection/ColorHeuristic.swift with the lines above.")


if __name__ == "__main__":
    main()
